language: ruby
os:
- linux
- osx
rvm:
- 2.5
before_install:
- gem install metanorma-cli
script:
- |
  for template in iso-rice international-standard
  do
    metanorma new test/$template --type iso --doctype $template --template . --overwrite
    metanorma compile test/$template/document.adoc
  done