version: '{build}'

environment:
  matrix:
    - RUBY_VERSION: 25

install:
  - ps: . { iwr -useb https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/appveyor.ps1 } | iex
  - refreshenv

build_script:
  - set PATH=C:\Ruby%RUBY_VERSION%\bin;%PATH%
  - gem install metanorma-cli

before_test:
  - ruby -v
  - gem -v

test_script:
  - for %%t in (iso-rice international-standard) do (
      metanorma new result\%%t --type iso --doctype %%t --template . --overwrite &
      metanorma compile %APPVEYOR_BUILD_FOLDER%\result\%%t\document.adoc
    )

on_finish:
  - 7z a %APPVEYOR_BUILD_FOLDER%\result.zip %APPVEYOR_BUILD_FOLDER%\result

artifacts:
  - path: result.zip
    name: result.zip