
[[terms]]
== Terms and definitions


=== translation type

methods used when translating between ODF and OOXML documents

[NOTE]
====
This Technical Report distinguishes four translation types:
* one way ODF to OOXML translation;
* one way OOXML to ODF translation;
* round trip ODF to OOXML to ODF translation;
* round trip OOXML to ODF to OOXML translation.
====

=== translation fidelity

quality of a translation process between the ODF and OOXML document formats

NOTE: Translation fidelity depends on document properties.

NOTE: Translation fidelity cannot be measured in an absolute manner; it depends on the intentions of the document's authors.


=== document property

description of different yet independent dimensions within the specification of a document

[NOTE]
====
As defined in 4.2 this Technical Report distinguishes the following document properties:
* presentation instructions;
* content;
* dynamic content;
* meta data;
* annotations and security;
* document parts.
====

NOTE: Document properties are implemented using document features.


// Illustration-purpose terms (these are not included in ISO/IEC TR 29166:2011 original standard)

[[term-script]]
=== script

particular graphic representation or class of representations of a set of characters used to write one or more languages

[.source]
<<ISO5127,clause="3.1.6.02">>


[[term-code]]
=== code

data representation in different forms according to a pre-established set of rules

[.source]
<<ISO639-2>>

